/**
 * Tool API Contract - Production Hardened Examples
 * 
 * This file demonstrates the production-ready tool API contract with:
 * - Strict version enforcement
 * - contractVersion in all responses
 * - requestId propagation
 * - Deprecation support
 * - Standardized error codes
 */

// ====================
// 1. STANDARD SUCCESS RESPONSE (v1 Contract)
// ====================
/*
{
  "success": true,
  "data": {
    // Tool-specific result data
  },
  "meta": {
    "tool": "emi_calculator",           // Tool slug
    "version": "v1",                     // Exact version used
    "contractVersion": "v1",             // API contract version
    "executionTimeMs": 12,               // Execution time
    "requestId": "req_abc123"            // When provided
  }
}
*/

// ====================
// 2. SUCCESS RESPONSE WITH DEPRECATION WARNING
// ====================
/*
{
  "success": true,
  "data": { ... },
  "meta": {
    "tool": "legacy_tool",
    "version": "v1",
    "contractVersion": "v1",
    "executionTimeMs": 8,
    "deprecation": {
      "deprecated": true,
      "message": "This tool version is deprecated",
      "sunsetDate": "2026-12-31",
      "daysRemaining": 248
    }
  }
}
*/

// ====================
// 3. STANDARD ERROR RESPONSE
// ====================
/*
{
  "success": false,
  "error": "TOOL_NOT_FOUND",            // Error code
  "message": "Tool not found: emi_calculator:v99",  // Human-readable
  "meta": {
    "contractVersion": "v1",
    "tool": "emi_calculator",
    "version": "v99",
    "requestId": "req_abc123"           // When provided
  }
}
*/

// ====================
// 4. ERROR CODES
// ====================
const ERROR_CODES = {
  // Version-related errors
  VERSION_REQUIRED: {
    status: 400,
    message: 'Version is required for tool execution. Use format: slug:version'
  },
  INVALID_TOOL_KEY: {
    status: 400,
    message: 'Invalid toolKey format. Expected: slug:version (e.g., emi_calculator:v1)'
  },
  TOOL_NOT_FOUND: {
    status: 404,
    message: 'Tool version does not exist'
  },
  TOOL_INACTIVE: {
    status: 400,
    message: 'Tool is not active'
  },
  TOOL_DEPRECATED: {
    status: 410,
    message: 'Tool version has expired'
  },
  
  // Execution errors
  VALIDATION_FAILED: {
    status: 400,
    message: 'Input validation failed'
  },
  INSUFFICIENT_CREDITS: {
    status: 402,
    message: 'Insufficient credits'
  },
  ENGINE_NOT_FOUND: {
    status: 500,
    message: 'Engine type not registered'
  },
  EXECUTION_ERROR: {
    status: 500,
    message: 'Tool execution failed'
  },
  QUEUE_LIMIT_EXCEEDED: {
    status: 429,
    message: 'Job queue limit exceeded'
  }
};

// ====================
// 5. TOOL KEY FORMAT VALIDATION
// ====================
// Regex: /^[a-z0-9_-]+:v\d+$/
// Valid examples:
//   - emi_calculator:v1
//   - pdf_merge:v2
//   - satbara_helper:v1
//   - image_resize:v10

// Invalid examples:
//   - emi_calculator       (missing version)
//   - emi-calculator:v1    (uppercase not allowed)
//   - emiCalculator:v1     (camelCase not allowed)
//   - emi_calculator:1     (version must be v\d+)
//   - emi_calculator:v     (version number required)

// ====================
// 6. EXAMPLE TOOL CONFIG WITH DEPRECATION
// ====================
const deprecatedToolConfig = {
  slug: 'legacy_calculator',
  version: 'v1',
  type: 'calculator',
  name: 'Legacy Calculator',
  description: 'This tool is being phased out',
  deprecated: true,
  sunsetDate: '2026-12-31',
  config: {
    inputs: [
      { name: 'value', type: 'number', label: 'Value', required: true }
    ],
    outputs: [
      { name: 'result', label: 'Result', format: 'number' }
    ]
  },
  active: true
};

// ====================
// 7. REQUEST ID PROPAGATION
// ====================
/*
requestId flows through:
1. Client sends: X-Request-Id header or generated by server
2. ToolExecutor.execute() - logs with requestId
3. UsageService.checkUsage() - logs with requestId
4. UsageService.consumeCredits() - logs with requestId
5. ExecutionLogger.logStart() - stored in DB
6. Queue job data - includes requestId
7. toolWorker - logs with requestId
8. Response meta - includes requestId

Example log output:
[req_abc123] Usage check: tool=emi_calculator, userId=guest, cost=1
[req_abc123] Consuming credits: tool=emi_calculator, userId=guest, cost=1
[req_abc123] Execution logged: tool=emi_calculator, logId=123
[req_abc123] Job added to queue: jobId=job_123, toolKey=emi_calculator:v1
[req_abc123] Job queued: logId=123, jobId=job_123
[req_abc123] Processing job: jobId=job_123, toolKey=emi_calculator:v1
[req_abc123] Job completed: jobId=job_123, time=45ms
*/

// ====================
// 8. CURL EXAMPLES
// ====================
/*
# Execute with requestId
curl -X POST http://localhost:3000/api/tools/emi_calculator:v1 \
  -H "Content-Type: application/json" \
  -H "X-Request-Id: req_my-unique-id" \
  -d '{
    "principal": 1000000,
    "rate": 8.5,
    "tenure": 240
  }'

# Response includes contractVersion and requestId:
# {
#   "success": true,
#   "data": { "emi": 8687.64, ... },
#   "meta": {
#     "tool": "emi_calculator",
#     "version": "v1",
#     "contractVersion": "v1",
#     "executionTimeMs": 12,
#     "requestId": "req_my-unique-id"
#   }
# }

# Error response:
# {
#   "success": false,
#   "error": "VERSION_REQUIRED",
#   "message": "Version is required for tool execution. Use format: slug:version",
#   "meta": {
#     "contractVersion": "v1",
#     "requestId": "req_my-unique-id"
#   }
# }
*/

// ====================
// 9. BACKWARD COMPATIBILITY (Metadata APIs only)
// ====================
/*
GET /api/tools/emi_calculator          → Returns latest version info
GET /api/tools/emi_calculator:v1       → Returns v1 info

POST /api/tools/emi_calculator:v1      → Executes v1 (version REQUIRED)
POST /api/tools/emi_calculator         → ERROR: VERSION_REQUIRED
*/

// ====================
// 10. ENGINE RESPONSE WRAPPING
// ====================
/*
Engines MUST return raw data. ToolExecutor wraps it:

// Engine returns:
{ emi: 8687.64, totalPayment: 2085033.60 }

// ToolExecutor.buildSuccessResponse wraps to:
{
  success: true,
  data: { emi: 8687.64, totalPayment: 2085033.60 },
  meta: {
    tool: "emi_calculator",
    version: "v1",
    contractVersion: "v1",
    executionTimeMs: 12
  }
}
*/

module.exports = {
  ERROR_CODES,
  deprecatedToolConfig
};